### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Ma-PC** [Navidfoumani/Series2Vec#2]
您好，requirements会继续更新吗？

**Comment by Navidfoumani** [comment]
Thank you for your comment. I've added the requirements file to the project.

**Comment by jumairamiller** [comment]
Hello, 

The requirements seem incomplete. I've already fixed the issue with the dependencies. However, there seems to be bugs in the code. A minor bug which I was able to correct was related to parsing data as the path specified in dataloader was incorrect. However, I am still facing some issues. Is the code up to date? 

I have been trying to reproduce your results for a few days now. I would greatly appreciate some clarifications :) 

Many thanks, 
Jumaira
