### ISSUE TITLE
Data link is unavailable

### ISSUE THREAD

**Issue by Rezvision** [Navidfoumani/Series2Vec#4]
Hi Navid,
I hope you are doing well. 

Do you have a working link for the dataset because the current link ( http://www.timeseriesclassification.com/Downloads/Archives/Multivariate2018_ts.zip) is down?
Thank you for this repository.

Kind regards,
Reza

**Comment by Navidfoumani** [comment]
Hi Reza,

Thank you for bringing this to my attention!
It seems they have updated their link addresses. 
Here is the new link for the dataset:
https://www.timeseriesclassification.com/aeon-toolkit/Archives/Multivariate2018_ts.zip

I'll also update the GitHub link accordingly.
